import { type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import CommandPalette from "../components/CommandPalette";

const Home: NextPage = () => {
  const { data: session, status } = useSession();
  if (status === "loading") {
    return <div>Loading...</div>;
  }
  console.log(session);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        {!session && (
          <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
            onClick={() => signIn('azure-ad')}>
            Sign In
          </button>
        )}
        {session && (
          <div className="flex flex-col items-center justify-center">
            <h1 className="text-2xl font-bold">{session.user?.name}</h1>
            <p className="text-gray-500">{session.user?.email}</p>
            <CommandPalette />
          </div>
        )}

      </main>
    </>
  );
};

export default Home;
