import { type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import CommandPalette from "../components/CommandPalette";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  if (status === "loading") {
    return <div>Loading...</div>;
  }
  console.log(session);
  return (
    <>
      <Head>
        <title>RelionHR</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-black">
        <main className="container mx-auto flex min-h-screen flex-col justify-center items-center p-4">
          {!session && (
            <>
              <h1 className="text-4xl cur font-bold text-white p-4">Welcome to RelionHR!</h1>
              <p className="text-white">
                <button
                  className="transition text-black border font-bold py-2 px-4 rounded bg-white
                  hover:bg-black hover:text-white duration-300"
                  onClick={() => signIn('azure-ad')}
                >
                  Sign in
                </button>
              </p>
            </>
          )}
          {session && (
            <CommandPalette />
          )}

        </main>
      </div>
    </>
  );
};

export default Home;
